name: Juxtapose CI

on:
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      Test:
        description: "Run Test On Linux With py3.8, py3.9, py3.10"
        default: false
        type: boolean

jobs:
  Test:
    if: github.repository == 'ziqinyeow/juxtapose' && (github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.Test == 'true'))
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # caching pip dependencies
      - name: Install requirements
        shell: bash # for Windows compatibility
        run: |
          python -m pip install --upgrade pip wheel
          pip install -e .
      - name: Check environment
        run: |
          echo "RUNNER_OS is ${{ runner.os }}"
          echo "GITHUB_EVENT_NAME is ${{ github.event_name }}"
          echo "GITHUB_WORKFLOW is ${{ github.workflow }}"
          echo "GITHUB_ACTOR is ${{ github.actor }}"
          echo "GITHUB_REPOSITORY is ${{ github.repository }}"
          echo "GITHUB_REPOSITORY_OWNER is ${{ github.repository_owner }}"
          python --version
          pip --version
          pip list
